routes/web.php
<?php

use App\Http\Controllers\LanguageController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/setLang',[LanguageController::class,'settingEdit'])->name('setLang');
Route::post('/setLang',[LanguageController::class,'settingUpdate'])->name('settingUpdate');

Route::get('/assignRole',[RoleController::class,'assignRoleToUser'])->name('assignRole');

Route::resource('user', UserController::class);
Route::resource('language', LanguageController::class);
Route::resource('setting', SettingController::class);
Route::resource('roles', RoleController::class);
Route::resource('permissions', PermissionController::class);
Route::resource('projects', ProjectController::class);
Route::resource('tasks', TaskController::class);

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;
    protected $guarded = [''];
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use App\Models\Task;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = Task::get();
        $projects = Project::get();
        return view('tasks.index' ,compact('tasks', 'projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    // public function create()
    // {
    //     $projects = Project::get();
    //     return view('tasks.create' ,compact('projects'));
    // }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());

        $tasks = new Task();
        $tasks->title = $request->title;
        $tasks->project = $request->project;
        $tasks->start_date = $request->start_date;
        $tasks->dua_date = $request->dua_date;
        $tasks->assign_to = $request->assign_to;
        $tasks->description = $request->description;
        $tasks->save();
        return redirect()->route('tasks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tasks = Task::find($id);
        $projects = Project::get();
        return view('tasks.edit' ,compact('tasks','projects'));

        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,  $id)
    {
        // dd($request->all());
        $tasks = Task::find($id);
        $tasks->title = $request->title;
        $tasks->project = $request->project;
        $tasks->start_date = $request->start_date;
        $tasks->dua_date = $request->dua_date;
        $tasks->assign_to = $request->assign_to;
        $tasks->description = $request->description;
        $tasks->save();
        return redirect()->route('tasks.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        //
    }
}

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Tasks</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('projects.index') }}">Tasks</a></li>
                        <li class="breadcrumb-item active">Edit</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <div class="container-fluid">
        <div class="row">

            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Update</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form action="" method="post">

                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6">

                                    <div class="form-group @error('title') has-error @enderror">
                                        <label for="title">Title<span class="text-danger">*</span></label>
                                        <input type="text" class="form-control" id="title"
                                            placeholder="Enter Project Title" name="title" value="{{ $tasks->title }}">
                                        @error('title')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>

                                    <div class="form-group @error('start_date') has-error @enderror">
                                        <label for="date">Start Date<span class="text-danger">*</span></label>
                                        <input type="text" class="form-control datepicker" name="start_date" id="start_date"
                                        value="{{ $tasks->start_date }}">
                                        @error('start_date')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                    <div class="form-group @error('dua_date') has-error @enderror">
                                        <label for="date">Due Date<span class="text-danger">*</span></label>
                                        <input type="text" class="form-control datepicker" name="dua_date" id="dua_date"
                                        value="{{ $tasks->dua_date }}">
                                        @error('dua_date')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>

                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="assign_to">Assign To</label>
                                        <select class="form-control" name="assign_to" id="assign_to">
                                            <option value="1 {{ $tasks->assign_to ==1 ? 'selected': '' }} ">Marketing</option>
                                            <option value="2 {{ $tasks->assign_to ==2 ? 'selected': '' }} ">Sales</option>
                                            <option value="3 {{ $tasks->assign_to ==3 ? 'selected': '' }} ">Human Resource</option>
                                            <option value="4 {{ $tasks->assign_to ==4 ? 'selected': '' }} ">Public Relations</option>
                                            <option value="5 {{ $tasks->assign_to ==5 ? 'selected': '' }} ">Research</option>
                                            <option value="6 {{ $tasks->assign_to ==6 ? 'selected': '' }} ">Finance</option>
                                        </select>

                                    </div>

                                    <div class="form-group">
                                        <label for="project">Project Category</label>
                                        <select class="form-control" name="project" id="project">
                                            <option value="1 {{ $tasks->project ==1 ? 'selected': '' }} ">Laravel</option>
                                            <option value="2 {{ $tasks->project ==2 ? 'selected': '' }} ">Yii</option>
                                            <option value="3 {{ $tasks->project ==3 ? 'selected': '' }} ">Zend</option>
                                            <option value="4 {{ $tasks->project ==4 ? 'selected': '' }} ">CatePhp</option>
                                            <option value="5 {{ $tasks->project ==5 ? 'selected': '' }} ">Codeigniter</option>
                                        </select>

                                    </div>

                                    <div class="form-group @error('description') has-error @enderror">
                                        <label for="description">Description<span class="text-danger">*</span></label>
                                        <textarea class="form-control" name="description" id="description"
                                            rows="3"> {{ $tasks->description }} </textarea>
                                        @error('description')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                </div>


                            </div>


                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer" style="text-align: center">
                            <button type="button" id="update_data" class="btn btn-primary">Update</button>
                        </div>
                    </form>

                </div>

            </div>
        </div>

    </div>
    @section('js')
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>

        <script>
            $(document).ready(function() {

                $('#update_data').on('click', function(e) {
                    e.preventDefault();

                    let title = $('#title').val();
                    let start_date = $('#start_date').val();
                    let dua_date = $('#dua_date').val();
                    let assign_to = $('#assign_to').val();
                    let project = $('#project').val();
                    let description = $('#description').val();

                    $.ajax({
                        url: "{{ route('tasks.update',$tasks->id) }}",
                        type: "POST",
                        data: {
                            "_token": "{{ csrf_token() }}",
                            "_token": "PUT",
                            title: title,
                            project: project,
                            start_date: start_date,
                            dua_date: dua_date,
                            assign_to: assign_to,
                            description: description,
                        },
                        success: function(response) {
                            console.log(response);
                            if (response) {
                                $('#success-message').text(response.success);
                                $("#taskForm")[0].reset();
                            }
                        },
                        error: function(response) {
                            console.log(' something missing ');
                            // $('#name-error').text(response.responseJSON.errors.name);
                            // $('#email-error').text(response.responseJSON.errors.email);
                            // $('#mobile-number-error').text(response.responseJSON.errors.mobile_number);
                            // $('#subject-error').text(response.responseJSON.errors.subject);
                            // $('#message-error').text(response.responseJSON.errors.message);
                        }
                    });
                });
            });
        </script>
    @endsection

@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('css')
<meta name="csrf-token" content="{{ csrf_token() }}">
@endsection

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Tasks</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('tasks.index') }}">Task</a></li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            {{-- <a href="{{ route('projects.create') }}" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Create</a> --}}
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal1">
                                Create
                            </button>
                        </div>

                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Title</th>
                                        <th>Project</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @forelse ($tasks as $task)
                                        <tr>
                                            <td>{{ $task->id }}</td>
                                            <td>{{ $task->title }}</td>
                                            <td>{{ $task->project }}</td>
                                            <td>
                                                <div class="btn-group">

                                                    <div class="btn-group">
                                                        <a href="{{ route('tasks.edit', $task->id) }}"
                                                            class="btn btn-primary">Update</a>

                                                            <form action="{{ route('tasks.destroy', $task->id) }}"
                                                                method="post">
                                                                @csrf
                                                                @method('DELETE')
                                                                <button type="submit"
                                                                    onclick="return confirm('Are you sure to detele')"
                                                                    class="btn btn-danger">Delete</button>
                                                            </form>
                                                    </div>
                                            </td>
                                        </tr>
                                    @empty
                                        <td>
                                            <span class="badge badge-danger">No Tasks</span>
                                        </td>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>


                </div>
            </div>
        </div>
        <div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Create</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form id="taskForm" method="post">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6">

                                    <div class="form-group @error('title') has-error @enderror">
                                        <label for="title">Title<span class="text-danger">*</span></label>
                                        <input type="text" class="form-control" id="title"
                                            placeholder="Enter Project Title" name="title" autocomplete="off">
                                        @error('title')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>

                                    <div class="form-group @error('start_date') has-error @enderror">
                                        <label for="date">Start Date<span class="text-danger">*</span></label>
                                        <input type="text" class="form-control datepicker" name="start_date" id="start_date"
                                            autocomplete="off">
                                        @error('start_date')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                    <div class="form-group @error('dua_date') has-error @enderror">
                                        <label for="date">Due Date<span class="text-danger">*</span></label>
                                        <input type="text" class="form-control datepicker" name="dua_date" id="dua_date"
                                            autocomplete="off">
                                        @error('dua_date')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>

                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="assign_to">Assign To</label>
                                        <select class="form-control" name="assign_to" id="assign_to">
                                            <option value="1">Marketing</option>
                                            <option value="2">Sales</option>
                                            <option value="3">Human Resource</option>
                                            <option value="4">Public Relations</option>
                                            <option value="5">Research</option>
                                            <option value="6">Finance</option>
                                        </select>

                                    </div>

                                    <div class="form-group">
                                        <label for="project">Project Category</label>
                                        <select class="form-control" name="project" id="project">
                                            @foreach ($projects as $project )

                                            <option value="{{ $project->id}}">{{ $project->name}}</option>

                                            @endforeach
                                        </select>

                                    </div>

                                    <div class="form-group @error('description') has-error @enderror">
                                        <label for="description">Description<span class="text-danger">*</span></label>
                                        <textarea class="form-control" name="description" id="description"
                                            rows="3"></textarea>
                                        @error('description')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                </div>


                            </div>


                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer" style="text-align: center">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>

    </section>
    @section('js')
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>

        <script>
            $(document).ready(function() {

                $('#taskForm').on('submit', function(e) {
                    e.preventDefault();

                    let title = $('#title').val();
                    let start_date = $('#start_date').val();
                    let dua_date = $('#dua_date').val();
                    let assign_to = $('#assign_to').val();
                    let project = $('#project').val();
                    let description = $('#description').val();

                    $.ajax({
                        url: "{{ route('tasks.index') }}",
                        type: "POST",
                        data: {
                            "_token": "{{ csrf_token() }}",
                            title: title,
                            project: project,
                            start_date: start_date,
                            dua_date: dua_date,
                            assign_to: assign_to,
                            description: description,
                        },
                        success: function(response) {
                            console.log(response);
                            if (response) {
                                $('#success-message').text(response.success);
                                $("#taskForm")[0].reset();
                                $('#exampleModal1').modal('hide');
                            }
                        },
                        error: function(response) {
                            console.log(' something missing ');
                            // $('#name-error').text(response.responseJSON.errors.name);
                            // $('#email-error').text(response.responseJSON.errors.email);
                            // $('#mobile-number-error').text(response.responseJSON.errors.mobile_number);
                            // $('#subject-error').text(response.responseJSON.errors.subject);
                            // $('#message-error').text(response.responseJSON.errors.message);
                        }
                    });
                });
            });
        </script>
    @endsection
@endsection

resources/views/tasks/show.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>project</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('projects.index') }}">project</a></li>
                        <li class="breadcrumb-item active">Edit</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <div class="container-fluid">
        <div class="row">

            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Create Project</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form action="{{ route('projects.edit', $projects->id) }}" method="post">
                        @csrf
                        <div class="card-body">

                            <div class="form-group @error('name') has-error @enderror">
                                <label for="name">Name<span class="text-danger">*</span></label>
                                <input type="text" class="form-control" placeholder="Enter Project Name" name="name" value="{{ $projects->name }}">
                                @error('name')
                                    <span class="text-danger"> {{ $message }} </span>
                                @enderror
                            </div>
                            <div class="form-group @error('progress') has-error @enderror">
                                <label for="progress">Progress <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" placeholder="Enter Parcentage %" name="progress" value="{{ $projects->progress }}">
                                @error('progress')
                                    <span class="text-danger"> {{ $message }} </span>
                                @enderror
                            </div>

                            <div class="form-group @error('deadline') has-error @enderror">
                                <label for="deadline">Deadline<span class="text-danger">*</span></label>
                                <input type="text" class="form-control" name="deadline" value="{{ $projects->deadline }}">
                                @error('deadline')
                                    <span class="text-danger"> {{ $message }} </span>
                                @enderror
                            </div>

                            <div class="form-group @error('status') has-error @enderror">
                                <label for="status">Status <span class="text-danger">*</span></label>
                                <select class="form-control" name="status" id="state">
                                    <option>Select</option>
                                    <option value="active"
                                        {{ $projects->status == 'active' ? 'selected' : '' }}>active</option>
                                    <option value="inactive"
                                        {{ $projects->status == 'inactive' ? 'selected' : '' }}>inactive</option>
                                </select>
                            </div>

                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer" style="text-align: center">
                            <a href="{{ route('projects.index') }}" class="btn btn-warning">Cancel</a>
                        </div>
                    </form>
                </div>

            </div>
        </div>

    </div>

@endsection